# Generated by Django 3.2 on 2023-01-12 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20230112_0358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='county',
            field=models.CharField(blank=True, default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='street_address2',
            field=models.CharField(blank=True, default=0, max_length=100),
        ),
    ]
